name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:12-alpine
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    -
      name: Checkout Repo
      uses: actions/checkout@v2
    -
      name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true
    -
      name: Pre Install
      run: sudo apt-get -yq install libpq-dev
    -
      name: Build
      run: |
        bundle install
        bundle exec rake db:create
        bundle exec rake db:migrate
    -
      name: Test
      run: bundle exec rails test
